apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    crowdstrike.com/component: manager
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: system
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: namespace
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    crowdstrike.com/component: manager
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: controller-manager
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: deployment
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        runAsNonRoot: true
        # Uncomment the following code when OpenShift < 4.11 is no longer supported.
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        env:
        - name: WATCH_NAMESPACE
        - name: OPERATOR_NAME
          value: "falcon-operator"
        #- name: RELATED_IMAGE_ADMISSION_CONTROLLER
        #  image: ""
        #- name: RELATED_IMAGE_NODE_SENSOR
        #  image: ""
        #- name: RELATED_IMAGE_SIDECAR_SENSOR
        #  image: ""
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          privileged: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
