{{- if ne .Values.serviceAccount.enabled false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: controller-manager-sa
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: serviceaccount
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
    {{- with .Values.serviceAccount.labels }}
    {{- with omit . "crowdstrike.com/component" "crowdstrike.com/created-by" "crowdstrike.com/instance" "crowdstrike.com/managed-by" "crowdstrike.com/name" "crowdstrike.com/part-of" "crowdstrike.com/provider" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "falcon-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
