apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: node-sensor-rolebinding
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: clusterrolebinding
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-operator-node-sensor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falcon-operator-node-sensor-role
subjects:
- kind: ServiceAccount
  name: falcon-operator-node-sensor
  namespace: falcon-operator-system
