
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    crowdstrike.com/component: metrics
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: controller-manager-metrics-monitor
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: servicemonitor
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
