apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    crowdstrike.com/component: kube-rbac-proxy
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: proxy-rolebinding
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: clusterrolebinding
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
