# permissions for end users to view falconcontainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconcontainer-viewer-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconcontainers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconcontainers/status
  verbs:
  - get
