# permissions for end users to edit falconadmissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: falconadmission-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: falcon-operator
    app.kubernetes.io/part-of: falcon-operator
    app.kubernetes.io/managed-by: kustomize
  name: falconadmission-editor-role
rules:
- apiGroups:
  - crowdstrike.com
  resources:
  - falconadmissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crowdstrike.com
  resources:
  - falconadmissions/status
  verbs:
  - get
