# permissions for end users to view falconconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconconfig-viewer-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconconfigs/status
  verbs:
  - get
