# permissions for end users to view falconnodesensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconnodesensor-viewer-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconnodesensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconnodesensors/status
  verbs:
  - get
