# permissions for end users to edit falconconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconconfig-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconconfigs/status
  verbs:
  - get
