# permissions for end users to edit falconcontainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falconcontainer-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconcontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconcontainers/status
  verbs:
  - get
