# permissions for end users to edit falconimageanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: falconimageanalyzer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: falcon-operator
    app.kubernetes.io/part-of: falcon-operator
    app.kubernetes.io/managed-by: kustomize
  name: falconimageanalyzer-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconimageanalyzers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconimageanalyzers/status
  verbs:
  - get
