apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: leader-election-rolebinding
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: rolebinding
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
