apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: falcon-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FalconConfig is the Schema for the falconconfigs API
      displayName: Falcon Config
      kind: FalconConfig
      name: falconconfigs.falcon.crowdstrike.com
      version: v1alpha1
  description: todo
  displayName: falcon-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  - runtime-protection
  links:
  - name: Falcon Operator
    url: https://falcon-operator.domain
  maturity: alpha
  provider:
    name: CrowdStrike
    url: https://github.com/CrowdStrike/falcon-operator
  version: 0.0.0
