# Falcon Container Installation.
#
# REQUIRED: Please fill in your CrowdStrike Falcon credentials bellow.
#
# To learn more about FalconContainer resource please consult documentation at
# https://github.com/CrowdStrike/falcon-operator/tree/main/docs/container

apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconContainer
metadata:
  labels:
    crowdstrike.com/component: sample
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: falcon-sidecar-sensor
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: falconcontainer
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-container-sensor
spec:
  falconSecret:
    enabled: true
    namespace: PLEASE_FILL_IN
    secretName: PLEASE_FILL_IN
  registry:
    type: crowdstrike
  falcon:
    trace: none
    tags:
      - sidecar
