# Falcon Node Sensor Installation.
#
# REQUIRED: Please fill in your CrowdStrike Falcon credentials bellow.
#
# To learn more about FalconNodeSensor resource please consult documentation at
# https://github.com/CrowdStrike/falcon-operator/tree/main/docs/node
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconNodeSensor
metadata:
  name: falcon-node-sensor
spec:
  # Add fields here
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  node:
    terminationGracePeriod: 30
  falcon:
    apd: null
    aph: null
    app: null
    billing: null
    cid: null
    feature: null
    message_log: null
    provisioning_token: null
    tags: null
    trace: none
