apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconNodeSensor
metadata:
  name: falcon-node-sensor
spec:
  # Add fields here
  node:
    terminationGracePeriod: 30
  falcon:
    apd: null
    aph: null
    app: null
    billing: null
    cid: null
    feature: null
    message_log: null
    provisioning_token: null
    tags: null
    trace: none
