apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconAdmission
metadata:
  labels:
    crowdstrike.com/component: sample
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: falcon-admission
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: falconadmission
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-kac
spec:
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  registry:
    type: crowdstrike
  falcon:
    trace: none
    tags:
      - admission_controller
  admissionConfig:
    # Example tolerations configuration
    tolerations:
      # Tolerate control-plane nodes
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      # Tolerate master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      # Custom toleration example
      - key: "dedicated"
        operator: "Equal"
        value: "admission"
        effect: "NoSchedule"