# Falcon Node Sensor Installation.
#
# REQUIRED: Please fill in your CrowdStrike Falcon credentials bellow.
#
# To learn more about FalconNodeSensor resource please consult documentation at
# https://github.com/CrowdStrike/falcon-operator/tree/main/docs/node
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconNodeSensor
metadata:
  labels:
    crowdstrike.com/component: sample
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: falcon-node-sensor
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: falconnodesensor
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-node-sensor
spec:
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
  falcon:
    trace: none
    tags:
      - daemonset
