# Falcon Container Installation.
#
# Example using all/many available options
---
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconContainer
metadata:
  name: default
spec:
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
    # (optional, default is derived from the API Key pair)
    cid: 00001111222233334444555566667777-12
  injector:
    serviceAccount:
      name: default
      annotations:
        # These are just examples, you wouldn't combine AWS & GKE roles at once
        eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/iam-role-name
        iam.gke.io/gcp-service-account: $GCP_SERVICE_ACCOUNT@$GCP_PROJECT_ID.iam.gserviceaccount.com
        annotation2: annotation-value
    falconctlOpts: '--apd=disabled --tags=test-cluster,tags1,tags2'
    disableDefaultNamespaceInjection: true
    disableDefaultPodInjection: false
    imagePullPolicy: Always
    imagePullSecret: your-pre-created-secret
    listenPort: 4433
    sensorResources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 50Mi
  registry:
    type: acr
    acr_name: falcon-sensor-repo
    tls:
      insecure_skip_verify: false
  version: 1.2.3.tagname
