---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 70435a7a.crowdstrike.com
kind: ConfigMap
metadata:
  name: falcon-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: falcon-operator-controller-manager
  name: falcon-operator-controller-manager
  namespace: falcon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: falcon-operator-controller-manager
  template:
    metadata:
      labels:
        control-plane: falcon-operator-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: quay.io/crowdstrike/falcon-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: falcon-operator
      terminationGracePeriodSeconds: 10
