# Adds namespace to all resources.
namespace: falcon-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: falcon-operator-

# Labels to add to all resources and selectors.
#labels:
#- includeSelectors: true
#  pairs:
#    someName: someValue

resources:
- ../crd
- ../rbac
- ../manager
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
#- ../webhook
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
#- ../certmanager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

patches:
- path: patches/auth_proxy_client_clusterrole.yaml
- path: patches/auth_proxy_role.yaml
- path: patches/auth_proxy_role_binding.yaml
- path: patches/auth_proxy_service.yaml
- path: patches/manager_patch.yaml
- path: patches/namespace_patch.yaml
- path: patches/falconnodesensor_role.yaml
- path: patches/falcon_falconimageanalyzer_role.yaml
- target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: falcondeployments.falcon.crowdstrike.com
  path: patches/log_volume_defaults_falcondeployments.yaml

