apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-sensor-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - cronjobs
      - daemonsets
      - deployments
      - ingresses
      - jobs
      - nodes
      - persistentvolumes
      - pods
      - replicasets
      - services
    verbs:
      - get
      - list
      - watch
