# Since the WATCH_NAMESPACE value needs to be null, we need to use a JSON Patch
# to add a null value because kustomize will strip it
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0/value
        value: null
