apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: falcon-operator
spec:
  channel: alpha
  name: falcon-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: falcon-operator.v0.5.4
