name: Operator Metadata Sanity

on:
  push:
    branches:
      - main
      - "maint-*"
  pull_request:
    branches:
      - main
      - "maint-*"

env:
  IMAGE: quay.io/crowdstrike/falcon-operator
  TAG: latest

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.18.x]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libbtrfs-dev libdevmapper-dev

      - name: Set release version
        if: github.ref_name != 'main' && github.base_ref != 'main'
        run: |
          TAG=$(grep ^VERSION Makefile | awk '{print $NF}')
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Setup the Operator SDK toolkit
        run: |
          mkdir -p $HOME/go/bin
          make operator-sdk

          IMAGE_TAG=${{ env.IMAGE }}:${{ env.TAG }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Ensure autogenerated stuff is in the best possible shape
        run: |
          export PATH=$HOME/go/bin:$PATH
          make manifests generate IMG=${{ env.IMAGE_TAG }}
          make bundle IMG=${{ env.IMAGE_TAG }}
          rm deploy/falcon-operator.yaml && make deploy/falcon-operator.yaml
          find ./bundle* -type f -exec sed -i -e 's/operator-sdk-v1.16.0+git/operator-sdk-v1.17.0/g' {} \;

          if [[ -n $(git status -s) ]] ; then
            echo
            echo -e "\e[31mGenerating manifests leaves tracked fields in a modified state."
            echo -e "\e[31mEnsure to include updated manifests in this PR."
            echo -e "\e[31mThis is usually done by running 'make manifests generate' and running 'git add ...' for the files that was modified by generating manifests.\e[0m"
            git status -s
            git diff --color
            exit 1
          fi
